apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  hostPath:
    path: /data/k8s-store-pv/pv-mongo
    type: DirectoryOrCreate

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongo
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mongo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dep-mongo
  template:
    metadata:
      labels:
        name: dep-mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: pvc-mongo
              mountPath: /data/db
              subPath: db
            - name: pvc-mongo
              mountPath: /data/configdb
              subPath: configdb
          resources:
            limits:
              cpu: 1
              memory: 256Mi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: yxh123

      volumes:
        - name: pvc-mongo
          persistentVolumeClaim:
            claimName: pvc-mongo


---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongo
  namespace: app
spec:
  selector:
    name: dep-mongo
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 31515